### PR TITLE
Update with all fixes

### PR DESCRIPTION
**Pull request by ckvsoft**
All changes and fixes should now be there

### CODE REVIEW

**Review by christian1980nrw — CHANGES_REQUESTED** [review]
Please pull back https://github.com/christian1980nrw/Spotmarket-Switcher/pull/109/commits/302a539ad4069a3dc52782b735a683f2d4f5f851 , this is already fixed and tested.

**Comment by ckvsoft** [comment]
The checks are never executed satisfactorily. Do you have a solution for that?
I tried something, but it didn't have much effect.
docker vebnus can't find crobtab, I have no idea.
Otherwise I tried to bypass exit 127, so I just copy the missing config.txt beforehand
I have no idea what bash version is installed on the Mac, so I can't find any errors.

**Comment by christian1980nrw** [comment]
@smoe Is developing with a Mac, thats his yml object. I think we can bypass exit 127 with a check if the sample config instead a config.txt exists and use the sample in that case.

**Comment by ckvsoft** [comment]
@christian1980nrw 

I've already tried to copy the sample-config.txt
That worked too.
But then there are other errors like crontab not found, then some error in the config check on the Mac. I undid everything. Don't know the venusOS Docker stuff. Everything that is installed there. Once I have fixed the crontab error, no authorization for s/services/rc.local is fixed, then ln is not possible... then I gave up

**Comment by smoe** [comment]
I just wished I could learn about the motivation behind those changes.

**Comment by ckvsoft** [comment]
@smoe 

These have already been reversed, but not yet merged. It just bothered me that the checks had errors. But more and more errors kept coming. Then I was never interested. Then that's just how it is.

**Comment by smoe** [comment]
@ckvsoft  ,  Thank you for your work. Back from the mobile (traveling) on the laptop I now have a better access to the commit logs. There are a few bits that I like a lot, others that would not have passed me, and "git rebase -i" prior to the merging of branches is not appreciated enough (also by @christian1980nrw :) ). The bits that would not have passed me are typically educational - to you or to me - so I wish I would have been involved, I just do not get any notification and frankly are not completely unhappy to have that as an excuse these days.

**Pull request merged**
