### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by ckvsoft**
a few little things, a small fix for commas instead of periods in the prices
Tested with aWattAr, I don't have a key for the others.
I'll keep watching to see how this goes.

### CODE REVIEW

**Comment by ckvsoft** [comment]
> @ckvsoft The script should work without bc command, please undo this change. Bc is not installed at Victron Venus OS systems by default and i dont want to install additional software. Regards Christian

Yes, I know that it should be installed. Then we have to think of something else.
Awk had an overflow during some conversions. As a result, a few millicent prices were not available

**Comment by ckvsoft** [comment]
fix 
If bc is not present, awk continues to be used

**Comment by christian1980nrw** [comment]
> > @ckvsoft The script should work without bc command, please undo this change. Bc is not installed at Victron Venus OS systems by default and i dont want to install additional software. Regards Christian
> 
> Yes, I know that it should be installed. Then we have to think of something else. Awk had an overflow during some conversions. As a result, a few millicent prices were not available

...maybe you can automatically replace the , by a . at the background if someone accitently uses it.

**Comment by ckvsoft** [comment]
> > > @ckvsoft The script should work without bc command, please undo this change. Bc is not installed at Victron Venus OS systems by default and i dont want to install additional software. Regards Christian
> > 
> > 
> > Yes, I know that it should be installed. Then we have to think of something else. Awk had an overflow during some conversions. As a result, a few millicent prices were not available
> 
> ...maybe you can automatically replace the , by a . at the background if someone accitently uses it.

I'll do that, but that wasn't the problem

**Pull request merged**
