### PR TITLE
merge @cksoft latest changes

### PR DESCRIPTION
**Pull request by christian1980nrw**

### CODE REVIEW

**Comment by christian1980nrw** [comment]
@ckvsoft I am not conviced of the new manage_fritz_sockets function.
Why it will fallback to shelly if fritz cannot be managed?
Before they were independent of each other.

**Comment by christian1980nrw** [comment]
I think this cannot be merged to main and need further testing.

**Comment by ckvsoft** [comment]
@christian1980nrw 
Apart from the fact that I made a mistake. Or copied it and then only changed the if, the two are independent of each other. Or does the information that things now continue with Shelly bother you? You can also leave it out. It was just log info for me

**Comment by christian1980nrw** [comment]
I will test that on Venus OS within the next days... Problem is, that my free time is short right now and I can't do it with the care it needs.

**Review by ckvsoft — CHANGES_REQUESTED** [review]
fixed typo

**Review by ckvsoft — APPROVED** [review]
fixed typo in #113

**Review by ckvsoft — APPROVED** [review]
I imagine I've already done that. Hmmm
It's definitely fixed

**Comment by christian1980nrw** [comment]
Main features tested at Venus OS. I will merge it to the main branch. Thank you for your work, we are getting better and better.

**Pull request merged**
