### PR TITLE
Further improved usability of the installer.

### PR DESCRIPTION
**Pull request by kLOsk**
This makes the installer more usable. There's an active yes / no selection instead of the 5 second time when installing to /tmp/foo/. Also improved the spacing of notifications and coloring.

### CODE REVIEW

**Comment by christian1980nrw** [comment]
Check on ubuntu-latest failed. Please have a look at https://github.com/christian1980nrw/Spotmarket-Switcher/actions/runs/6591460881/job/17910409753?pr=105 @kLOsk

**Comment by kLOsk** [comment]
@christian1980nrw actually script runs fine. Why is the check asking for
```
tput: No value for $TERM and no -T specified
```

? $TERM is not defined in the script...

**Comment by kLOsk** [comment]
mhm seems to be related to this: https://stackoverflow.com/questions/29979966/tput-no-value-for-term-and-no-t-specified-error-logged-by-cron-process

Not sure if I should apply the workaround mentioned. The installer should always be triggered by a shell...

**Comment by christian1980nrw** [comment]
> @christian1980nrw actually script runs fine. Why is the check asking for
> 
> ```
> tput: No value for $TERM and no -T specified
> ```
> 
> ? $TERM is not defined in the script...

I verified the changes on Victron Venus OS too now, but the script is not running with this changes.
I will comment it out in the master until a solution is found.

#bold=$(tput bold)
#underline=$(tput sgr 0 1)
#reset=$(tput sgr0)
#purple=$(tput setaf 171)
#red=$(tput setaf 1)
#green=$(tput setaf 76)
#tan=$(tput setaf 3)
#blue=$(tput setaf 38)

**Comment by christian1980nrw** [comment]
see https://github.com/christian1980nrw/Spotmarket-Switcher/commit/818b8837158a4e4431040efa75951a66d3eceff4

**Comment by christian1980nrw** [comment]
@kLOsk If you agree we can remove the color topic first and come back to it maybe later and i will merge the other changes?

**Comment by kLOsk** [comment]
Ah, yes thanks. I haven't tested with victronOS yet, sorry. Bit hard to debug on a live system. Can you give me some insight into your dev setup? Can I run the installer and avoid modifying crontab?

**Comment by kLOsk** [comment]
I just tested with a test script on my Cerbo GX and it actually works fine to modifiy colours. Can you execute `echo $TERM` on your Venus OS?

Screenshot 2023-10-21 at 08 16 20

**Comment by kLOsk** [comment]
@christian1980nrw could you resolve the conflict and try my fix?

**Comment by christian1980nrw** [comment]
> I just tested with a test script on my Cerbo GX and it actually works fine to modifiy colours. Can you execute `echo $TERM` on your Venus OS?
> 
> Screenshot 2023-10-21 at 08 16 20

root@raspberrypi4:~# echo TERM
TERM
root@raspberrypi4:~# echo $TERM
xterm

I will check your fix i bit later but the different $TERM outputs should be combined with a if condition.

**Comment by ckvsoft** [comment]
why don't you just use escape sequences for the colors?

**Comment by christian1980nrw** [comment]
@kLOsk Please check the latest main. We are successfully using colors now. Please resubmit the other changes with another pull, i am a bit clumsy with github, i didnt find an option to accept only parts of the changes.

**Pull request closed without merging**
